name: Meshkit Error Codes Utility Runner
on:
  push:
    branches:
      - 'master'
    paths:
      - '**.go'

jobs:
  Update-error-codes:
    name: Error codes utility
    if: github.repository == 'khulnasoft/meshkit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # token here with write access to meshkit repo
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}
          ref: 'master'

      - name: Setup Go
        uses: actions/setup-go@master
        with:
          go-version: ${{ secrets.GO_VERSION }}

      - name: Run utility
        run: |
          go run github.com/khulnasoft/meshkit/cmd/errorutil -d . update --skip-dirs meshplay -i ./helpers -o ./helpers

      # to update errorutil* files in meshkit repo
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          commit_user_email: ci@khulnasoft.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: "run error codes utility"
          file_pattern: helpers/ **.go

      # to push changes to meshplay docs
      - name: Checkout meshplay
        uses: actions/checkout@master
        with:
          repository: 'khulnasoft/meshplay'
          # token with write access to meshplay repository
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: 'meshplay'
          ref: 'master'

      - name: Update and push docs
        run: |
          echo '{ "errors_export": "" }' | jq --slurpfile export ./helpers/errorutil_errors_export.json '.errors_export = $export[0]' > ./meshplay/docs/_data/errorref/meshkit_errors_export.json

          cd ./meshplay
          git config user.name l5io
          git config user.email ci@khulnasoft.com
          if git diff --exit-code --quiet
          then
            echo "No changes to commit"
            exit
          fi
          git add ./docs/_data/errorref/meshkit_errors_export.json
          git commit -m "[Docs] Error Code Reference: Updated codes for MeshKit library" --signoff
          git push origin master
